name: generate pacman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman
        uses: Platane/snk@v3
        with:
          github_user_name: Ahmed-Yasser1231
          outputs: |
            dist/pacman-contribution-graph.svg?palette=github
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push Pacman
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
